// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vurnvrdsowmskhvxwmfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1cm52cmRzb3dtc2todnh3bWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjA0MDMsImV4cCI6MjA3MTczNjQwM30.VB9pWGt6Sn6cKvO0xB5TPWl9tZfhIfIivJFjLZ-vR08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});